### ISSUE TITLE
Migration error in version upgrade to 1.0.0-alpha

### ISSUE THREAD

**Issue by Tjoosten** [JosephSilber/bouncer#117]
**Version**: Laravel 5.3
**AFFECTS:** Laravel application installation, application testing

**Stack trace:**

```php 
[2016-08-19 15:57:22] local.ERROR: ErrorException: array_map(): Argument #2 should be an array in /Users/tim/Documents/idev-git/IMA/database/migrations/2016_08_19_153713_upgrade_to_bouncer_02.php:76
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'array_map(): Ar...', '/Users/tim/Docu...', 76, Array)
#1 /Users/tim/Documents/idev-git/IMA/database/migrations/2016_08_19_153713_upgrade_to_bouncer_02.php(76): array_map(Object(Closure), Object(Illuminate\Support\Collection))
#2 /Users/tim/Documents/idev-git/IMA/database/migrations/2016_08_19_153713_upgrade_to_bouncer_02.php(54): UpgradeToBouncer02->migrateUserRoles()
#3 /Users/tim/Documents/idev-git/IMA/database/migrations/2016_08_19_153713_upgrade_to_bouncer_02.php(18): UpgradeToBouncer02->migrateData()
#4 /Users/tim/Documents/idev-git/IMA/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(162): UpgradeToBouncer02->up()
#5 /Users/tim/Documents/idev-git/IMA/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(130): Illuminate\Database\Migrations\Migrator->runUp('2016_08_19_1537...', 1, false)
#6 /Users/tim/Documents/idev-git/IMA/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(97): Illuminate\Database\Migrations\Migrator->runMigrationList(Array, Array)
#7 /Users/tim/Documents/idev-git/IMA/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(65): Illuminate\Database\Migrations\Migrator->run(Array, Array)
#8 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#9 /Users/tim/Documents/idev-git/IMA/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#10 /Users/tim/Documents/idev-git/IMA/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#11 /Users/tim/Documents/idev-git/IMA/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /Users/tim/Documents/idev-git/IMA/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /Users/tim/Documents/idev-git/IMA/vendor/symfony/console/Application.php(818): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /Users/tim/Documents/idev-git/IMA/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /Users/tim/Documents/idev-git/IMA/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /Users/tim/Documents/idev-git/IMA/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(111): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /Users/tim/Documents/idev-git/IMA/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 {main}  
```

**Code**: 

```php
$records = array_map(function ($pivot) use ($type) {
            return [
                'role_id'     => $pivot->role_id,
                'entity_type' => $type,
                'entity_id'   => $pivot->user_id,
            ];
        }, $pivots);
```
**Possible fix:**

```php
$records = array_map(function ($pivot) use ($type) {
            return [
                'role_id'     => $pivot->role_id,
                'entity_type' => $type,
                'entity_id'   => $pivot->user_id,
            ];
        }, $pivots->toArray());
```

**NOTE:** I will do a pr within 4 hours

**Comment by JosephSilber** [comment]
Fixed. Thanks.
