### ISSUE TITLE
Install failing

### ISSUE THREAD

**Issue by jesperbjerke** [JosephSilber/bouncer#388]
running `composer require silber/bouncer v1.0.0-rc.4`

Generates the following output:

```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing silber/bouncer (v1.0.0-rc.4): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In Models.php line 288:

  Class 'App\User' not found


Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

I searched the issues and I've seen this error discussed before, but in my case I can't even get it to install properly.
I have configured the `auth` config to use my User model. I've cleared config cache before installing, tried reinstalling, tried a previous version of bouncer etc etc.

Have to remove the package to get my application running properly again.

Running Laravel v5.7.25

Any ideas?

**Comment by JosephSilber** [comment]
> I have configured the `auth` config to use my User model.

Can you share the config?

**Comment by jesperbjerke** [comment]
Sure, here:

```
[

    /*
    |--------------------------------------------------------------------------
    | Authentication Defaults
    |--------------------------------------------------------------------------
    |
    | This option controls the default authentication "guard" and password
    | reset options for your application. You may change these defaults
    | as required, but they're a perfect start for most applications.
    |
    */

    'defaults' => [
        'guard' => env('AUTH_GAURD', 'api'),
        'passwords' => 'users',
    ],

    /*
    |--------------------------------------------------------------------------
    | Authentication Guards
    |--------------------------------------------------------------------------
    |
    | Next, you may define every authentication guard for your application.
    | Of course, a great default configuration has been defined for you
    | here which uses session storage and the Eloquent user provider.
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | Supported: "session", "token"
    |
    */

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'firebase'
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | User Providers
    |--------------------------------------------------------------------------
    |
    | All authentication drivers have a user provider. This defines how the
    | users are actually retrieved out of your database or other storage
    | mechanisms used by this application to persist your user's data.
    |
    | If you have multiple user tables or models you may configure multiple
    | sources which represent each model / table. These sources may then
    | be assigned to any extra authentication guards you have defined.
    |
    | Supported: "database", "eloquent"
    |
    */

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\Shared\User::class,
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Resetting Passwords
    |--------------------------------------------------------------------------
    |
    | You may specify multiple password reset configurations if you have more
    | than one user table or model in the application and you want to have
    | separate password reset settings based on the specific user types.
    |
    | The expire time is the number of minutes that the reset token should be
    | considered valid. This security feature keeps tokens short-lived so
    | they have less time to be guessed. You may change this as needed.
    |
    */

    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],

];
```

The regular `Auth::user()` methods and similar works fine.

**Comment by JosephSilber** [comment]
@jesperbjerke it seems like you're using firebase directly, without utilizing Laravel's user provider.

This is a unique case, so Bouncer can't figure it out on its own. Instead, [you should tell Bouncer explicitly which user model to use](https://github.com/JosephSilber/bouncer/blob/a8b7176136f7db83a57e7f8aa72019160a9f2d09/readme.md#user-model):

```php
Bouncer::useUserModel(\App\Models\Shared\User::class);
```

**Comment by jesperbjerke** [comment]
Okay, thanks, I'll try it out when I get the chance. Was looking for some information about that in the documentation, but obviously not hard enough.

**Comment by jesperbjerke** [comment]
I just got time to try this out, (updated to rc.5), and indeed it works if I revert the auth to use the default user provider. However, as soon as I change back to my firebase provider, all bouncer stuff through the command line triggers the same error (although now with a different linenumber). I have added `Bouncer::useUserModel(\App\Models\Shared\User::class);` to my AppServiceProvider in the boot method.

For example, I cannot run my seeder to add bouncer roles and abilities without getting:

```
$ php artisan db:seed --class=BouncerSeeder

In Models.php line 317:

  Class 'App\User' not found
```

```
Class 'App\User' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'App\\User' not found at .../vendor/silber/bouncer/src/Database/Models.php:317)
[stacktrace]
#0 .../vendor/silber/bouncer/src/Database/Models.php(276): Silber\\Bouncer\\Database\\Models::make('App\\\\User', Array)
#1 .../vendor/silber/bouncer/src/Database/Models.php(87): Silber\\Bouncer\\Database\\Models::user()
#2 .../vendor/silber/bouncer/src/BouncerServiceProvider.php(145): Silber\\Bouncer\\Database\\Models::setUsersModel('App\\\\User')
#3 .../vendor/silber/bouncer/src/BouncerServiceProvider.php(35): Silber\\Bouncer\\BouncerServiceProvider->setUserModel()
#4 [internal function]: Silber\\Bouncer\\BouncerServiceProvider->boot()
```

According to this stacktrace it seems to force the App\User namespace? I even tried calling the useUserModel method directly in the seeder but same thing.

**Comment by JosephSilber** [comment]
Can you post the full stack trace?

**Comment by antonioribeiro** [comment]
If the app config is cached, it may not be able to get the new configuration because config:cache gives this error before clearing and caching configuration, just delete the cache manually:

```
rm bootstrap/cache/config.php
```
